server:
  port: 8082
  context-path: /ui
  session:
   cookie:
     name: UISESSION
security:
  basic:
    enabled: false
  oauth2:
    client:
      access-token-uri: http://localhost:8081/auth/oauth/token
      client-id: ClientId
      client-secret: secret
      user-authorization-uri: http://localhost:8081/auth/oauth/authorize
    resource:
      user-info-uri: http://localhost:8081/auth/rest/hello/principal
spring:
  thymeleaf:
    cache: false



